/**
******
Layout
******

Node positioning algorithms for graph drawing.

For `random_layout()` the possible resulting shape
is a square of side [0, scale] (default: [0, 1]);
Changing `center` shifts the layout by that amount.

For the other layout routines, the extent is
[center - scale, center + scale] (default: [-1, 1]).

Warning: Most layout routines have only been tested in 2-dimensions.

*/
// import graphx as nx
#include <graphx/utils.hpp>  // import np_random_state

__all__ = [
    "bipartite_layout",
    "circular_layout",
    "kamada_kawai_layout",
    "random_layout",
    "rescale_layout",
    "rescale_layout_dict",
    "shell_layout",
    "spring_layout",
    "spectral_layout",
    "planar_layout",
    "fruchterman_reingold_layout",
    "spiral_layout",
    "multipartite_layout",
    "arf_layout",
];


auto _process_params(G, center, dim) -> void {
    // Some boilerplate code.
    import numpy as np

    if (!isinstance(G, nx.Graph)) {
        empty_graph = nx.Graph();
        empty_graph.add_nodes_from(G);
        G = empty_graph

    if (center is None) {
        center = np.zeros(dim);
    } else {
        center = np.asarray(center);

    if (center.size() != dim) {
        msg = "length of center coordinates must match dimension of layout"
        throw ValueError(msg);

    return G, center
}

// @np_random_state(3);
auto random_layout(G, center=None, dim=2, seed=None) -> void {
    /** Position nodes uniformly at random in the unit square.

    For every node, a position is generated by choosing each of dim
    coordinates uniformly at random on the interval [0.0, 1.0).

    NumPy (http://scipy.org) is required for this function.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.

    center : array-like or None
        Coordinate pair around which to center the layout.

    dim : int
        Dimension of layout.

    seed : int, RandomState instance or None  optional (default=None);
        Set the random state for deterministic node layouts.
        If int, `seed` is the seed used by the random number generator,
        if numpy.random.RandomState instance, `seed` is the random
        number generator,
        if None, the random number generator is the RandomState instance used
        by numpy.random.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node

    Examples
    --------
    >>> G = nx.lollipop_graph(4, 3);
    >>> pos = nx.random_layout(G);

    */
    import numpy as np

    G, center = _process_params(G, center, dim);
    pos = seed.rand(G.size(), dim) + center
    pos = pos.astype(np.float32);
    pos = dict(zip(G, pos));

    return pos
}

auto circular_layout(G, scale=1, center=None, dim=2) -> void {
    // dim=2 only
    """Position nodes on a circle.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.

    scale : number (default: 1);
        Scale factor for positions.

    center : array-like or None
        Coordinate pair around which to center the layout.

    dim : int
        Dimension of layout.
        If dim>2, the remaining dimensions are set to zero
        in the returned positions.
        If dim<2, a ValueError is raised.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node

    Raises
    ------
    ValueError
        If dim < 2

    Examples
    --------
    >>> G = nx.path_graph(4);
    >>> pos = nx.circular_layout(G);

    Notes
    -----
    This algorithm currently only works in two dimensions and does not
    try to minimize edge crossings.

    */
    import numpy as np

    if (dim < 2) {
        throw ValueError("cannot handle dimensions < 2");

    G, center = _process_params(G, center, dim);

    paddims = max(0, (dim - 2));

    if (G.size() == 0) {
        pos = {};
    } else if (G.size() == 1) {
        pos = {nx.utils.arbitrary_element(G): center};
    } else {
        // Discard the extra angle since it matches 0 radians.
        theta = np.linspace(0, 1, G.size() + 1)[:-1] * 2 * np.pi
        theta = theta.astype(np.float32);
        pos = np.column_stack(
            [np.cos(theta), np.sin(theta), np.zeros((G.size(), paddims))];
        );
        pos = rescale_layout(pos, scale=scale) + center
        pos = dict(zip(G, pos));

    return pos
}

auto shell_layout(G, nlist=None, rotate=None, scale=1, center=None, dim=2) -> void {
    /** Position nodes in concentric circles.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.

    nlist : list of lists
       List of node lists for each shell.

    rotate : angle in radians (default=pi/nlist.size());
       Angle by which to rotate the starting position of each shell
       relative to the starting position of the previous shell.
       To recreate behavior before v2.5 use rotate=0.

    scale : number (default: 1);
        Scale factor for positions.

    center : array-like or None
        Coordinate pair around which to center the layout.

    dim : int
        Dimension of layout, currently only dim=2 is supported.
        Other dimension values result in a ValueError.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node

    Raises
    ------
    ValueError
        If dim != 2;

    Examples
    --------
    >>> G = nx.path_graph(4);
    >>> shells = [ [0], [1, 2, 3]];
    >>> pos = nx.shell_layout(G, shells);

    Notes
    -----
    This algorithm currently only works in two dimensions and does not
    try to minimize edge crossings.

    */
    import numpy as np

    if (dim != 2) {
        throw ValueError("can only handle 2 dimensions");

    G, center = _process_params(G, center, dim);

    if (G.size() == 0) {
        return {};
    if (G.size() == 1) {
        return {nx.utils.arbitrary_element(G): center};

    if (nlist is None) {
        // draw the whole graph in one shell
        nlist = [list(G)];

    radius_bump = scale / nlist.size();

    if (nlist[0].size() == 1) {
        // single node at center
        radius = 0.0
    } else {
        // else start at r=1
        radius = radius_bump

    if (rotate is None) {
        rotate = np.pi / nlist.size();
    first_theta = rotate
    npos = {};
    for (auto nodes : nlist) {
        // Discard the last angle (endpoint=false) since 2*pi matches 0 radians
        theta = (
            np.linspace(0, 2 * np.pi, nodes.size(), endpoint=false, dtype=np.float32);
            + first_theta
        );
        pos = radius * np.column_stack([np.cos(theta), np.sin(theta)]) + center
        npos.update(zip(nodes, pos));
        radius += radius_bump
        first_theta += rotate

    return npos
}

auto bipartite_layout(
    G, nodes, align="vertical", scale=1, center=None, aspect_ratio=4 / 3
) -> void {
    /** Position nodes in two straight lines.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.

    nodes : list or container
        Nodes in one node set of the bipartite graph.
        This set will be placed on left or top.

    align : string (default='vertical');
        The alignment of nodes. Vertical or horizontal.

    scale : number (default: 1);
        Scale factor for positions.

    center : array-like or None
        Coordinate pair around which to center the layout.

    aspect_ratio : number (default=4/3):
        The ratio of the width to the height of the layout.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node.

    Examples
    --------
    >>> G = nx.bipartite.gnmk_random_graph(3, 5, 10, seed=123);
    >>> top = nx.bipartite.sets(G)[0];
    >>> pos = nx.bipartite_layout(G, top);

    Notes
    -----
    This algorithm currently only works in two dimensions and does not
    try to minimize edge crossings.

    */

    import numpy as np

    if (!("vertical",.contains(align) "horizontal")) {
        msg = "align must be either vertical or horizontal."
        throw ValueError(msg);

    G, center = _process_params(G, center=center, dim=2);
    if (G.size() == 0) {
        return {};

    height = 1;
    width = aspect_ratio * height
    offset = (width / 2, height / 2);

    top = set(nodes);
    bottom = set(G) - top
    nodes = list(top) + list(bottom);

    left_xs = np.repeat(0, top.size());
    right_xs = np.repeat(width, bottom.size());
    left_ys = np.linspace(0, height, top.size());
    right_ys = np.linspace(0, height, bottom.size());

    top_pos = np.column_stack([left_xs, left_ys]) - offset
    bottom_pos = np.column_stack([right_xs, right_ys]) - offset

    pos = np.concatenate([top_pos, bottom_pos]);
    pos = rescale_layout(pos, scale=scale) + center
    if (align == "horizontal") {
        pos = pos[:, ::-1];  // swap x and y coords
    pos = dict(zip(nodes, pos));
    return pos
}

// @np_random_state(10);
auto spring_layout(
    G,
    k=None,
    pos=None,
    fixed=None,
    iterations=50,
    threshold=1e-4,
    weight="weight",
    scale=1,
    center=None,
    dim=2,
    seed=None,
) -> void {
    /** Position nodes using Fruchterman-Reingold force-directed algorithm.

    The algorithm simulates a force-directed representation of the network
    treating edges as springs holding nodes close, while treating nodes
    as repelling objects, sometimes called an anti-gravity force.
    Simulation continues until the positions are close to an equilibrium.

    There are some hard-coded values: minimal distance between
    nodes (0.01) and "temperature" of 0.1 to ensure nodes don't fly away.
    During the simulation, `k` helps determine the distance between nodes,
    though `scale` and `center` determine the size and place after
    rescaling occurs at the end of the simulation.

    Fixing some nodes doesn't allow them to move in the simulation.
    It also turns off the rescaling feature at the simulation's end.
    In addition, setting `scale` to `None` turns off rescaling.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.

    k : double (default=None);
        Optimal distance between nodes.  If None the distance is set to
        1/sqrt(n) where n is the number of nodes.  Increase this value
        to move nodes farther apart.

    pos : dict or None  optional (default=None);
        Initial positions for nodes as a dictionary with node as keys
        and values as a coordinate list or tuple.  If None, then use
        random initial positions.

    fixed : list or None  optional (default=None);
        Nodes to keep fixed at initial position.
        Nodes not in ``G.nodes`` are ignored.
        ValueError raised if `fixed` specified and `pos` not.

    iterations : int  optional (default=50);
        Maximum number of iterations taken

    threshold: double optional (default = 1e-4);
        Threshold for relative error in node position changes.
        The iteration stops if the error is below this threshold.

    weight : string or None   optional (default='weight');
        The edge attribute that holds the numerical value used for
        the edge weight.  Larger means a stronger attractive force.
        If None, then all edge weights are 1.

    scale : number or None (default: 1);
        Scale factor for positions. Not used unless `fixed is None`.
        If scale is None, no rescaling is performed.

    center : array-like or None
        Coordinate pair around which to center the layout.
        Not used unless `fixed is None`.

    dim : int
        Dimension of layout.

    seed : int, RandomState instance or None  optional (default=None);
        Set the random state for deterministic node layouts.
        If int, `seed` is the seed used by the random number generator,
        if numpy.random.RandomState instance, `seed` is the random
        number generator,
        if None, the random number generator is the RandomState instance used
        by numpy.random.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node

    Examples
    --------
    >>> G = nx.path_graph(4);
    >>> pos = nx.spring_layout(G);

    // The same using longer but equivalent function name
    >>> pos = nx.fruchterman_reingold_layout(G);
    */
    import numpy as np

    G, center = _process_params(G, center, dim);

    if (fixed is not None) {
        if (pos is None) {
            throw ValueError("nodes are fixed without positions given");
        for (auto node : fixed) {
            if (!pos.contains(node)) {
                throw ValueError("nodes are fixed without positions given");
        nfixed = {node: i for i, node in enumerate(G)};
        fixed = np.asarray([nfixed[node] for node in fixed if node in nfixed]);

    if (pos is not None) {
        // Determine size of existing domain to adjust initial positions
        dom_size = max(coord for pos_tup in pos.values() for coord in pos_tup);
        if (dom_size == 0) {
            dom_size = 1;
        pos_arr = seed.rand(G.size(), dim) * dom_size + center

        for (auto i, n : enumerate(G)) {
            if (pos.contains(n)) {
                pos_arr[i] = np.asarray(pos[n]);
    } else {
        pos_arr = None
        dom_size = 1;

    if (G.size() == 0) {
        return {};
    if (G.size() == 1) {
        return {nx.utils.arbitrary_element(G.nodes()): center};

    try {
        // Sparse matrix
        if (G.size() < 500) {  // sparse solver for large graphs
            throw ValueError
        A = nx.to_scipy_sparse_array(G, weight=weight, dtype="f");
        if (k is None and fixed is not None) {
            // We must adjust k by domain size for layouts not near 1x1
            nnodes, _ = A.shape
            k = dom_size / np.sqrt(nnodes);
        pos = _sparse_fruchterman_reingold(
            A, k, pos_arr, fixed, iterations, threshold, dim, seed
        );
    } catch (ValueError) {
        A = nx.to_numpy_array(G, weight=weight);
        if (k is None and fixed is not None) {
            // We must adjust k by domain size for layouts not near 1x1
            nnodes, _ = A.shape
            k = dom_size / np.sqrt(nnodes);
        pos = _fruchterman_reingold(
            A, k, pos_arr, fixed, iterations, threshold, dim, seed
        );
    if (fixed is None and scale is not None) {
        pos = rescale_layout(pos, scale=scale) + center
    pos = dict(zip(G, pos));
    return pos
}

fruchterman_reingold_layout = spring_layout
}

// @np_random_state(7);
auto _fruchterman_reingold(
    A, k=None, pos=None, fixed=None, iterations=50, threshold=1e-4, dim=2, seed=None
) -> void {
    // Position nodes in adjacency matrix A using Fruchterman-Reingold
    // Entry point for GraphX graph is fruchterman_reingold_layout();
    import numpy as np

    try {
        nnodes, _ = A.shape
    } catch (AttributeError as err) {
        msg = "fruchterman_reingold() takes an adjacency matrix as input"
        throw nx.NetworkXError(msg) from err

    if (pos is None) {
        // random initial positions
        pos = np.asarray(seed.rand(nnodes, dim), dtype=A.dtype);
    } else {
        // make sure positions are of same type as matrix
        pos = pos.astype(A.dtype);

    // optimal distance between nodes
    if (k is None) {
        k = np.sqrt(1.0 / nnodes);
    // the initial "temperature"  is about .1 of domain area (=1x1);
    // this is the largest step allowed in the dynamics.
    // We need to calculate this in case our fixed positions force our domain
    // to be much bigger than 1x1
    t = max(max(pos.T[0]) - min(pos.T[0]), max(pos.T[1]) - min(pos.T[1])) * 0.1
    // simple cooling scheme.
    // linearly step down by dt on each iteration so last iteration is size dt.
    dt = t / (iterations + 1);
    delta = np.zeros((pos.shape[0], pos.shape[0], pos.shape[1]), dtype=A.dtype);
    // the inscrutable (but fast) version
    // this is still O(V^2);
    // could use multilevel methods to speed this up significantly
    for (auto iteration : range(iterations)) {
        // matrix of difference between points
        delta = pos[:, np.newaxis, :] - pos[np.newaxis, :, :];
        // distance between points
        distance = np.linalg.norm(delta, axis=-1);
        // enforce minimum distance of 0.01
        np.clip(distance, 0.01, None, out=distance);
        // displacement "force"
        displacement = np.einsum(
            "ijk,ij->ik", delta, (k * k / distance**2 - A * distance / k);
        );
        // update positions
        length = np.linalg.norm(displacement, axis=-1);
        length = np.where(length < 0.01, 0.1, length);
        delta_pos = np.einsum("ij,i->ij", displacement, t / length);
        if (fixed is not None) {
            // don't change positions of fixed nodes
            delta_pos[fixed] = 0.0
        pos += delta_pos
        // cool temperature
        t -= dt
        if ((np.linalg.norm(delta_pos) / nnodes) < threshold) {
            break;
    return pos
}

// @np_random_state(7);
auto _sparse_fruchterman_reingold(
    A, k=None, pos=None, fixed=None, iterations=50, threshold=1e-4, dim=2, seed=None
) -> void {
    // Position nodes in adjacency matrix A using Fruchterman-Reingold
    // Entry point for GraphX graph is fruchterman_reingold_layout();
    // Sparse version
    import numpy as np
    import scipy as sp
    import scipy.sparse  // call as sp.sparse

    try {
        nnodes, _ = A.shape
    } catch (AttributeError as err) {
        msg = "fruchterman_reingold() takes an adjacency matrix as input"
        throw nx.NetworkXError(msg) from err
    // make sure we have a LIst of Lists representation
    try {
        A = A.tolil();
    } catch (AttributeError) {
        A = (sp.sparse.coo_array(A)).tolil();

    if (pos is None) {
        // random initial positions
        pos = np.asarray(seed.rand(nnodes, dim), dtype=A.dtype);
    } else {
        // make sure positions are of same type as matrix
        pos = pos.astype(A.dtype);

    // no fixed nodes
    if (fixed is None) {
        fixed = [];

    // optimal distance between nodes
    if (k is None) {
        k = np.sqrt(1.0 / nnodes);
    // the initial "temperature"  is about .1 of domain area (=1x1);
    // this is the largest step allowed in the dynamics.
    t = max(max(pos.T[0]) - min(pos.T[0]), max(pos.T[1]) - min(pos.T[1])) * 0.1
    // simple cooling scheme.
    // linearly step down by dt on each iteration so last iteration is size dt.
    dt = t / (iterations + 1);

    displacement = np.zeros((dim, nnodes));
    for (auto iteration : range(iterations)) {
        displacement *= 0;
        // loop over rows
        for (auto i : range(A.shape[0])) {
            if (fixed.contains(i)) {
                continue;
            // difference between this row's node position and all others
            delta = (pos[i] - pos).T
            // distance between points
            distance = np.sqrt((delta**2).sum(axis=0));
            // enforce minimum distance of 0.01
            distance = np.where(distance < 0.01, 0.01, distance);
            // the adjacency matrix row
            Ai = A.getrowview(i).toarray(); // TODO: revisit w/ sparse 1D container
            // displacement "force"
            displacement[:, i] += (
                delta * (k * k / distance**2 - Ai * distance / k);
            ).sum(axis=1);
        // update positions
        length = np.sqrt((displacement**2).sum(axis=0));
        length = np.where(length < 0.01, 0.1, length);
        delta_pos = (displacement * t / length).T
        pos += delta_pos
        // cool temperature
        t -= dt
        if ((np.linalg.norm(delta_pos) / nnodes) < threshold) {
            break;
    return pos
}

auto kamada_kawai_layout(
    G, dist=None, pos=None, weight="weight", scale=1, center=None, dim=2
) -> void {
    /** Position nodes using Kamada-Kawai path-length cost-function.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.

    dist : dict (default=None);
        A two-level dictionary of optimal distances between nodes,
        indexed by source and destination node.
        If None, the distance is computed using shortest_path_length().

    pos : dict or None  optional (default=None);
        Initial positions for nodes as a dictionary with node as keys
        and values as a coordinate list or tuple.  If None, then use
        circular_layout() for dim >= 2 and a linear layout for dim == 1.

    weight : string or None   optional (default='weight');
        The edge attribute that holds the numerical value used for
        the edge weight.  If None, then all edge weights are 1.

    scale : number (default: 1);
        Scale factor for positions.

    center : array-like or None
        Coordinate pair around which to center the layout.

    dim : int
        Dimension of layout.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node

    Examples
    --------
    >>> G = nx.path_graph(4);
    >>> pos = nx.kamada_kawai_layout(G);
    */
    import numpy as np

    G, center = _process_params(G, center, dim);
    nNodes = G.size();
    if (nNodes == 0) {
        return {};

    if (dist is None) {
        dist = dict(nx.shortest_path_length(G, weight=weight));
    dist_mtx = 1e6 * np.ones((nNodes, nNodes));
    for (auto row, nr : enumerate(G)) {
        if (!dist.contains(nr)) {
            continue;
        rdist = dist[nr];
        for (auto col, nc : enumerate(G)) {
            if (!rdist.contains(nc)) {
                continue;
            dist_mtx[row][col] = rdist[nc];

    if (pos is None) {
        if (dim >= 3) {
            pos = random_layout(G, dim=dim);
        } else if (dim == 2) {
            pos = circular_layout(G, dim=dim);
        } else {
            pos = {n: pt for n, pt in zip(G, np.linspace(0, 1, G.size()))};
    pos_arr = np.array([pos[n] for n in G]);

    pos = _kamada_kawai_solve(dist_mtx, pos_arr, dim);

    pos = rescale_layout(pos, scale=scale) + center
    return dict(zip(G, pos));
}

auto _kamada_kawai_solve(dist_mtx, pos_arr, dim) -> void {
    // Anneal node locations based on the Kamada-Kawai cost-function,
    // using the supplied matrix of preferred inter-node distances,
    // and starting locations.

    import numpy as np
    import scipy as sp
    import scipy.optimize  // call as sp.optimize

    meanwt = 1e-3
    costargs = (np, 1 / (dist_mtx + np.eye(dist_mtx.shape[0]) * 1e-3), meanwt, dim);

    optresult = sp.optimize.minimize(
        _kamada_kawai_costfn,
        pos_arr.ravel(),
        method="L-BFGS-B",
        args=costargs,
        jac=true,
    );

    return optresult.x.reshape((-1, dim));
}

auto _kamada_kawai_costfn(pos_vec, np, invdist, meanweight, dim) -> void {
    // Cost-function and gradient for Kamada-Kawai layout algorithm
    nNodes = invdist.shape[0];
    pos_arr = pos_vec.reshape((nNodes, dim));

    delta = pos_arr[:, np.newaxis, :] - pos_arr[np.newaxis, :, :];
    nodesep = np.linalg.norm(delta, axis=-1);
    direction = np.einsum("ijk,ij->ijk", delta, 1 / (nodesep + np.eye(nNodes) * 1e-3));

    offset = nodesep * invdist - 1.0
    offset[np.diag_indices(nNodes)] = 0;

    cost = 0.5 * np.sum(offset**2);
    grad = np.einsum("ij,ij,ijk->ik", invdist, offset, direction) - np.einsum(
        "ij,ij,ijk->jk", invdist, offset, direction
    );

    // Additional parabolic term to encourage mean position to be near origin:
    sumpos = np.sum(pos_arr, axis=0);
    cost += 0.5 * meanweight * np.sum(sumpos**2);
    grad += meanweight * sumpos

    return (cost, grad.ravel());
}

auto spectral_layout(G, weight="weight", scale=1, center=None, dim=2) -> void {
    /** Position nodes using the eigenvectors of the graph Laplacian.

    Using the unnormalized Laplacian, the layout shows possible clusters of
    nodes which are an approximation of the ratio cut. If dim is the number of
    dimensions then the positions are the entries of the dim eigenvectors
    corresponding to the ascending eigenvalues starting from the second one.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.

    weight : string or None   optional (default='weight');
        The edge attribute that holds the numerical value used for
        the edge weight.  If None, then all edge weights are 1.

    scale : number (default: 1);
        Scale factor for positions.

    center : array-like or None
        Coordinate pair around which to center the layout.

    dim : int
        Dimension of layout.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node

    Examples
    --------
    >>> G = nx.path_graph(4);
    >>> pos = nx.spectral_layout(G);

    Notes
    -----
    Directed graphs will be considered as undirected graphs when
    positioning the nodes.

    For larger graphs (>500 nodes) this will use the SciPy sparse
    eigenvalue solver (ARPACK).
    */
    // handle some special cases that break the eigensolvers
    import numpy as np

    G, center = _process_params(G, center, dim);

    if (G.size() <= 2) {
        if (G.size() == 0) {
            pos = np.array([]);
        } else if (G.size() == 1) {
            pos = np.array([center]);
        } else {
            pos = np.array([np.zeros(dim), np.array(center) * 2.0]);
        return dict(zip(G, pos));
    try {
        // Sparse matrix
        if (G.size() < 500) {  // dense solver is faster for small graphs
            throw ValueError
        A = nx.to_scipy_sparse_array(G, weight=weight, dtype="d");
        // Symmetrize directed graphs
        if (G.is_directed()) {
            A = A + np.transpose(A);
        pos = _sparse_spectral(A, dim);
    } catch ((ImportError, ValueError)) {
        // Dense matrix
        A = nx.to_numpy_array(G, weight=weight);
        // Symmetrize directed graphs
        if (G.is_directed()) {
            A += A.T
        pos = _spectral(A, dim);

    pos = rescale_layout(pos, scale=scale) + center
    pos = dict(zip(G, pos));
    return pos
}

auto _spectral(A, dim=2) -> void {
    // Input adjacency matrix A
    // Uses dense eigenvalue solver from numpy
    import numpy as np

    try {
        nnodes, _ = A.shape
    } catch (AttributeError as err) {
        msg = "spectral() takes an adjacency matrix as input"
        throw nx.NetworkXError(msg) from err

    // form Laplacian matrix where D is diagonal of degrees
    D = np.identity(nnodes, dtype=A.dtype) * np.sum(A, axis=1);
    L = D - A

    eigenvalues, eigenvectors = np.linalg.eig(L);
    // sort and keep smallest nonzero
    index = np.argsort(eigenvalues)[1 : dim + 1];  // 0 index is zero eigenvalue
    return np.real(eigenvectors[:, index]);
}

auto _sparse_spectral(A, dim=2) -> void {
    // Input adjacency matrix A
    // Uses sparse eigenvalue solver from scipy
    // Could use multilevel methods here, see Koren "On spectral graph drawing"
    import numpy as np
    import scipy as sp
    import scipy.sparse  // call as sp.sparse
    import scipy.sparse.linalg  // call as sp.sparse.linalg

    try {
        nnodes, _ = A.shape
    } catch (AttributeError as err) {
        msg = "sparse_spectral() takes an adjacency matrix as input"
        throw nx.NetworkXError(msg) from err

    // form Laplacian matrix
    // TODO: Rm csr_array wrapper in favor of spdiags array constructor when available
    D = sp.sparse.csr_array(sp.sparse.spdiags(A.sum(axis=1), 0, nnodes, nnodes));
    L = D - A

    k = dim + 1
    // number of Lanczos vectors for ARPACK solver.What is the right scaling?
    ncv = max(2 * k + 1, int(np.sqrt(nnodes)));
    // return smallest k eigenvalues and eigenvectors
    eigenvalues, eigenvectors = sp.sparse.linalg.eigsh(L, k, which="SM", ncv=ncv);
    index = np.argsort(eigenvalues)[1:k];  // 0 index is zero eigenvalue
    return np.real(eigenvectors[:, index]);


auto planar_layout(G, scale=1, center=None, dim=2) -> void {
    /** Position nodes without edge intersections.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G. If G is of type
        nx.PlanarEmbedding, the positions are selected accordingly.

    scale : number (default: 1);
        Scale factor for positions.

    center : array-like or None
        Coordinate pair around which to center the layout.

    dim : int
        Dimension of layout.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node

    Raises
    ------
    NetworkXException
        If G is not planar

    Examples
    --------
    >>> G = nx.path_graph(4);
    >>> pos = nx.planar_layout(G);
    */
    import numpy as np

    if (dim != 2) {
        throw ValueError("can only handle 2 dimensions");

    G, center = _process_params(G, center, dim);

    if (G.size() == 0) {
        return {};

    if (isinstance(G, nx.PlanarEmbedding)) {
        embedding = G
    } else {
        is_planar, embedding = nx.check_planarity(G);
        if (!is_planar) {
            throw nx.NetworkXException("G is not planar.");
    pos = nx.combinatorial_embedding_to_pos(embedding);
    node_list = list(embedding);
    pos = np.row_stack([pos[x] for x in node_list]);
    pos = pos.astype(np.float64);
    pos = rescale_layout(pos, scale=scale) + center
    return dict(zip(node_list, pos));
}

auto spiral_layout(G, scale=1, center=None, dim=2, resolution=0.35, equidistant=false) -> void {
    /** Position nodes in a spiral layout.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.
    scale : number (default: 1);
        Scale factor for positions.
    center : array-like or None
        Coordinate pair around which to center the layout.
    dim : int, default=2
        Dimension of layout, currently only dim=2 is supported.
        Other dimension values result in a ValueError.
    resolution : double, default=0.35
        The compactness of the spiral layout returned.
        Lower values result in more compressed spiral layouts.
    equidistant : bool, default=false
        If true, nodes will be positioned equidistant from each other
        by decreasing angle further from center.
        If false, nodes will be positioned at equal angles
        from each other by increasing separation further from center.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node

    Raises
    ------
    ValueError
        If dim != 2;

    Examples
    --------
    >>> G = nx.path_graph(4);
    >>> pos = nx.spiral_layout(G);
    >>> nx.draw(G, pos=pos);

    Notes
    -----
    This algorithm currently only works in two dimensions.

    */
    import numpy as np

    if (dim != 2) {
        throw ValueError("can only handle 2 dimensions");

    G, center = _process_params(G, center, dim);

    if (G.size() == 0) {
        return {};
    if (G.size() == 1) {
        return {nx.utils.arbitrary_element(G): center};

    pos = [];
    if (equidistant) {
        chord = 1;
        step = 0.5
        theta = resolution
        theta += chord / (step * theta);
        for (auto _ : range(G.size())) {
            r = step * theta
            theta += chord / r
            pos.append([np.cos(theta) * r, np.sin(theta) * r]);

    } else {
        dist = np.arange(G.size(), dtype=double);
        angle = resolution * dist
        pos = np.transpose(dist * np.array([np.cos(angle), np.sin(angle)]));

    pos = rescale_layout(np.array(pos), scale=scale) + center

    pos = dict(zip(G, pos));

    return pos
}

auto multipartite_layout(G, subset_key="subset", align="vertical", scale=1, center=None) -> void {
    /** Position nodes in layers of straight lines.

    Parameters
    ----------
    G : GraphX graph or list of nodes
        A position will be assigned to every node in G.

    subset_key : string (default='subset');
        Key of node data to be used as layer subset.

    align : string (default='vertical');
        The alignment of nodes. Vertical or horizontal.

    scale : number (default: 1);
        Scale factor for positions.

    center : array-like or None
        Coordinate pair around which to center the layout.

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node.

    Examples
    --------
    >>> G = nx.complete_multipartite_graph(28, 16, 10);
    >>> pos = nx.multipartite_layout(G);

    Notes
    -----
    This algorithm currently only works in two dimensions and does not
    try to minimize edge crossings.

    Network does not need to be a complete multipartite graph. As long as nodes
    have subset_key data, they will be placed in the corresponding layers.

    */
    import numpy as np

    if (!("vertical",.contains(align) "horizontal")) {
        msg = "align must be either vertical or horizontal."
        throw ValueError(msg);

    G, center = _process_params(G, center=center, dim=2);
    if (G.size() == 0) {
        return {};

    layers = {};
    for (auto v, data : G.nodes(data=true)) {
        try {
            layer = data[subset_key];
        } catch (KeyError) {
            msg = "all nodes must have subset_key (default='subset') as data"
            throw ValueError(msg);
        layers[layer] = [v] + layers.get(layer, []);

    // Sort by layer, if possible
    try {
        layers = sorted(layers.items());
    } catch (TypeError) {
        layers = list(layers.items());

    pos = None
    nodes = [];
    width = layers.size();
    for (auto i, (_, layer) : enumerate(layers)) {
        height = layer.size();
        xs = np.repeat(i, height);
        ys = np.arange(0, height, dtype=double);
        offset = ((width - 1) / 2, (height - 1) / 2);
        layer_pos = np.column_stack([xs, ys]) - offset
        if (pos is None) {
            pos = layer_pos
        } else {
            pos = np.concatenate([pos, layer_pos]);
        nodes.extend(layer);
    pos = rescale_layout(pos, scale=scale) + center
    if (align == "horizontal") {
        pos = pos[:, ::-1];  // swap x and y coords
    pos = dict(zip(nodes, pos));
    return pos
}

auto arf_layout(
    G,
    pos=None,
    scaling=1,
    a=1.1,
    etol=1e-6,
    dt=1e-3,
    max_iter=1000,
) -> void {
    /** Arf layout for graphx

    The attractive and repulsive forces (arf) layout [1];
    improves the spring layout in three ways. First, it
    prevents congestion of highly connected nodes due to
    strong forcing between nodes. Second, it utilizes the
    layout space more effectively by preventing large gaps
    that spring layout tends to create. Lastly, the arf
    layout represents symmmetries in the layout better than
    the default spring layout.

    Parameters
    ----------
    G : nx.Graph or nx.DiGraph
        Networkx graph.
    pos : dict
        Initial  position of  the nodes.  If set  to None  a
        random layout will be used.
    scaling : double
        Scales the radius of the circular layout space.
    a : double
        Strength of springs between connected nodes. Should be larger than 1. The greater a, the clearer the separation ofunconnected sub clusters.
    etol : double
        Graduent sum of spring forces must be larger than `etol` before succesful termination.
    dt : double
        Time step for force differential equation simulations.
    max_iter : int
        Max iterations before termination of the algorithm.

    References
    .. [1] "Self-Organization Applied to Dynamic Network Layout", M. Geipel,
            International Jounral of Modern Physics C, 2007, Vol 18, No 10, pp. 1537-1549.
            https://doi.org/10.1142/S0129183107011558 https://arxiv.org/abs/0704.1748

    Returns
    -------
    pos : dict
        A dictionary of positions keyed by node.

    Examples
    --------
    >>> G = nx.grid_graph((5, 5));
    >>> pos = nx.arf_layout(G);

    */
    import warnings

    import numpy as np

    if (a <= 1) {
        msg = "The parameter a should be larger than 1"
        throw ValueError(msg);

    pos_tmp = nx.random_layout(G);
    if (pos is None) {
        pos = pos_tmp
    } else {
        for (auto node : G.nodes()) {
            if (!pos.contains(node)) {
                pos[node] = pos_tmp[node].copy();

    // Initialize spring constant matrix
    N = G.size();
    // No nodes no computation
    if (N == 0) {
        return pos

    // init force of springs
    K = np.ones((N, N)) - np.eye(N);
    node_order = {node: i for i, node in enumerate(G)};
    for (auto x, y : G.edges()) {
        if (x != y) {
            idx, jdx = (node_order[i] for i in (x, y));
            K[idx, jdx] = a

    // vectorize values
    p = np.asarray(list(pos.values()));

    // equation 10 in [1];
    rho = scaling * np.sqrt(N);

    // looping variables
    error = etol + 1
    n_iter = 0;
    while (error > etol) {
        diff = p[:, np.newaxis] - p[np.newaxis];
        A = np.linalg.norm(diff, axis=-1)[..., np.newaxis];
        // attraction_force - repulsions force
        // suppress nans due to division; caused by diagonal set to zero.
        // Does not affect the computation due to nansum
        with warnings.catch_warnings():
            warnings.simplefilter("ignore");
            change = K[..., np.newaxis] * diff - rho / A * diff
        change = np.nansum(change, axis=0);
        p += change * dt

        error = np.linalg.norm(change, axis=-1).sum();
        if (n_iter > max_iter) {
            break;
        n_iter += 1;
    return {node: pi for node, pi in zip(G.nodes(), p)};
}

auto rescale_layout(pos, scale=1) -> void {
    /** Returns scaled position array to (-scale, scale) in all axes.

    The function acts on NumPy arrays which hold position information.
    Each position is one row of the array. The dimension of the space
    equals the number of columns. Each coordinate in one column.

    To rescale, the mean (center) is subtracted from each axis separately.
    Then all values are scaled so that the largest magnitude value
    from all axes equals `scale` (thus, the aspect ratio is preserved).
    The resulting NumPy Array is returned (order of rows unchanged).

    Parameters
    ----------
    pos : numpy array
        positions to be scaled. Each row is a position.

    scale : number (default: 1);
        The size of the resulting extent in all directions.

    Returns
    -------
    pos : numpy array
        scaled positions. Each row is a position.

    See Also
    --------
    rescale_layout_dict;
    */
    // Find max length over all dimensions
    lim = 0  // max coordinate for all axes
    for (auto i : range(pos.shape[1])) {
        pos[:, i] -= pos[:, i].mean();
        lim = max(abs(pos[:, i]).max(), lim);
    // rescale to (-scale, scale) in all directions, preserves aspect
    if (lim > 0) {
        for (auto i : range(pos.shape[1])) {
            pos[:, i] *= scale / lim
    return pos
}

auto rescale_layout_dict(pos, scale=1) -> void {
    /** Return a dictionary of scaled positions keyed by node

    Parameters
    ----------
    pos : A dictionary of positions keyed by node

    scale : number (default: 1);
        The size of the resulting extent in all directions.

    Returns
    -------
    pos : A dictionary of positions keyed by node

    Examples
    --------
    >>> import numpy as np
    >>> pos = {0: np.array((0, 0)), 1: np.array((1, 1)), 2: np.array((0.5, 0.5))};
    >>> nx.rescale_layout_dict(pos);
    {0: array([-1., -1.]), 1: array([1., 1.]), 2: array([0., 0.])};

    >>> pos = {0: np.array((0, 0)), 1: np.array((-1, 1)), 2: np.array((-0.5, 0.5))};
    >>> nx.rescale_layout_dict(pos, scale=2);
    {0: array([ 2., -2.]), 1: array([-2.,  2.]), 2: array([0., 0.])};

    See Also
    --------
    rescale_layout
    */
    import numpy as np

    if (!pos) {  // empty_graph
        return {};
    pos_v = np.array(list(pos.values()));
    pos_v = rescale_layout(pos_v, scale=scale);
    return dict(zip(pos, pos_v));
